# The gRPC port to bind
bindPort: 8080

# The Intel Attestation Service endpoint to use
attestationServiceUrl: https://api.trustedservices.intel.com/sgx/dev

# The size of the connection handling thread pool. Note that this also limits the number of parallel connections to the
# enclave
threadPoolSize: 8

# The EPID SPID to use when quoting.
# This is set to a placeholder value, to be replaced by an R3-specific SPID in EnclaveletHostConfiguration.defaults
epidSpid: "<placeholder>"

# Subscription key for connecting to Intel Attestation Service.
# This is set to a placeholder value, to be replaced by an R3 key in EnclaveletHostConfiguration.defaults which grants
# us access to the test version of IAS.
iasSubscriptionKey: "<placeholder>"

# What type of EPID quote we want (LINKABLE or UNLINKABLE)
epidQuoteType: LINKABLE

# What mode to load the enclave in: SIMULATION, DEBUG, RELEASE. Note that only enclaves signed with a whitelisted key
# may be loaded in RELEASE mode.
enclaveLoadMode: RELEASE

# When the enclavelet is loaded in SIMULATION mode the enclavelet host will issue an attestation report backed by a mock
# certificate (see class [MockAttestationCertStore]) to simplify testing, unless this flag is set to false.
mockAttestationServiceInSimulation: true
