# To render this docsite:
#
# 1. Install mkdocs (https://mkdocs.org) by running "pip install mkdocs"
# 2. Install mkdocs-material theme: "pip install mkdocs-material"
# 3. Run "mkdocs serve" in this directory and browse to localhost. Edits to the files will be reflected immediately.

site_name: Conclave documentation
use_directory_urls: false

nav:
  - Welcome: index.md
  - Enclaves: enclaves.md
  - Development:
    - Tutorial:
        - Compiling and running: tutorial.md
        - Writing hello world: writing-hello-world.md
        - Container Gradle: container-gradle.md
    - Conclave architecture: architecture.md
    - Mail: mail.md
    - Threads: threads.md
    - JavaScript: javascript.md
    - Configuration options for enclaves: enclave-configuration.md
    - Security discussion: security.md
    - API: api/index.html
    - API migration notes: api-changes.md
  - Operations:
    - Server deployment:
      - Machine setup: machine-setup.md
      - IAS: ias.md
      - Deploying to Azure: azure.md
    - Enclave signing: signing.md
    - Renewability: renewability.md
  - FAQ: faq.md

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  features:
    - tabs

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


google_analytics:
  - 'UA-87760032-7'
  - 'auto'