# To render this docsite:
#
# 1. Install mkdocs (https://mkdocs.org) by running "pip install mkdocs"
# 2. Install mkdocs-material theme: "pip install mkdocs-material"
# 3. Run "mkdocs serve" in this directory and browse to localhost. Edits to the files will be reflected immediately.

site_name: Conclave documentation
use_directory_urls: false

nav:
  - Welcome: index.md
  - Enclaves: enclaves.md
  - Development:
    - Tutorials:
        - Compiling and running: tutorial.md
        - Writing hello world: writing-hello-world.md
        - Writing a CorDapp: writing-cordapps.md
        - Container Gradle: container-gradle.md
    - Design topics:
        - Conclave architecture: architecture.md
        - Mail: mail.md
        - Security discussion: security.md
    - Reference:
        - Threads: threads.md
        - JavaScript: javascript.md
        - File system: filesystem.md
        - Configuration options for enclaves: enclave-configuration.md
    - API:
        - JavaDocs: api/index.html
        - Migration notes: api-changes.md
  - Operations:
    - Server deployment:
      - System requirements: system-requirements.md
      - Machine setup: machine-setup.md
      - IAS: ias.md
      - Deploying to Azure: azure.md
    - Upgrades:
      - Enclave signing: signing.md
      - Renewability: renewability.md
  - FAQ: faq.md

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


google_analytics:
  - 'UA-87760032-7'
  - 'auto'
